apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-admin
  labels:
    k8s-app: kube-system
  namespace: kube-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-admin
  labels:
    k8s-app: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: kube-admin
    namespace: kube-system

---

apiVersion: v1
kind: Secret
metadata:
  name: kube-admin-token
  namespace: kube-system
  labels:
    k8s-app: kube-system
  annotations:
    kubernetes.io/service-account.name: kube-admin
type: kubernetes.io/service-account-token
